# Generated by generate_ui_template_catalog.py
TSERVER_UI_TEMPLATE_FILES = \
	../sdk-ios-ui/src/TserverTemplateRegistry.mm \
	../sdk-ios-ui/src/TserverNativeTemplateRenderer.mm \
	../sdk-ios-ui/src/TserverSimpleUiPack.mm \
	../sdk-ios-ui/templates/apple_glass/AppleGlass.mm \
	../sdk-ios-ui/templates/apple_glass/screens/AppleGlassDeviceVerify.mm \
	../sdk-ios-ui/templates/apple_glass/screens/AppleGlassKeyEntry.mm \
	../sdk-ios-ui/templates/apple_glass/screens/AppleGlassLoading.mm \
	../sdk-ios-ui/templates/apple_glass/screens/AppleGlassResult.mm \
	../sdk-ios-ui/templates/cyber_terminal/CyberTerminal.mm \
	../sdk-ios-ui/templates/cyber_terminal/screens/CyberTerminalDeviceVerify.mm \
	../sdk-ios-ui/templates/cyber_terminal/screens/CyberTerminalKeyEntry.mm \
	../sdk-ios-ui/templates/cyber_terminal/screens/CyberTerminalLoading.mm \
	../sdk-ios-ui/templates/cyber_terminal/screens/CyberTerminalResult.mm
