// AUTO-GENERATED by scripts/embed_client_api_key.sh — do not edit.
// CLIENT_API_KEY anti-hex embed:
//  - dual XOR masks
//  - shuffled byte order (perm)
//  - split high/low nibble tables with decoy bits
//  - no contiguous 64-char hex alphabet / no plain key string
#include <stddef.h>
#include <stdint.h>
#include <string.h>

// Non-secret SHA-256 fingerprint of the 64-character CLIENT_API_KEY. This is
// release provenance only; it cannot authenticate a request or reconstruct key bytes.
static const char kTserverClientApiKeyFingerprint[] = "11a139c9d858d1c022a1575e7af4c09c539a8ae76370a8260a2db87b2dd04f79";

static const uint8_t kTserverKeyHi[32] = {
  0x31, 0x75, 0x56, 0x9f, 0x31, 0x46, 0x59, 0xce, 0xc7, 0xa0, 0x55, 0x9d, 0x55, 0xb7, 0xbd, 0x0b,
  0x31, 0x7b, 0x55, 0x9c, 0x3b, 0x4f, 0x58, 0xc7, 0xc6, 0xa3, 0x57, 0x9e, 0x59, 0xb4, 0xbb, 0x05
};

static const uint8_t kTserverKeyLo[32] = {
  0x98, 0xd1, 0xfd, 0x3e, 0x9a, 0xef, 0xf3, 0x6a, 0x66, 0x08, 0xf0, 0x37, 0xf3, 0x19, 0x11, 0xa5,
  0x9b, 0xd6, 0xf6, 0x3e, 0x93, 0xe2, 0xfd, 0x63, 0x69, 0x06, 0xfd, 0x33, 0xfc, 0x1c, 0x1a, 0xaf
};

static const uint8_t kTserverKeyMaskA[32] = {
  0x1c, 0xb0, 0x15, 0x62, 0xc1, 0xe2, 0x00, 0x5f, 0xc9, 0x31, 0x27, 0x2e, 0x24, 0x4d, 0x96, 0x74,
  0x1b, 0x5e, 0x11, 0x19, 0xb9, 0xec, 0x06, 0x5f, 0x85, 0xa3, 0x26, 0x8c, 0xb5, 0xad, 0xbd, 0x4c
};

static const uint8_t kTserverKeyMaskB[32] = {
  0x48, 0xd3, 0xd0, 0xfc, 0x8e, 0xf5, 0xde, 0xb5, 0xd6, 0xbc, 0xe8, 0x6d, 0x58, 0xe0, 0xec, 0xdb,
  0x9c, 0xd0, 0x1a, 0x7d, 0x05, 0x34, 0xe6, 0x12, 0x69, 0xb7, 0x71, 0x0d, 0xac, 0xff, 0xa8, 0x9d
};

static const uint8_t kTserverKeyInvPerm[32] = {
  15, 24, 29, 27, 21, 3, 25, 2, 26, 30, 7, 12, 17, 8, 6, 0,
  11, 14, 13, 22, 18, 28, 10, 19, 23, 31, 4, 16, 1, 9, 20, 5
};


#ifdef __cplusplus
extern "C" {
#endif

// Reconstruct 64 lowercase hex chars into out[0..63], out[64]=0. Returns 0 on success.
int TserverFillClientApiKeyHex(char *out, size_t outCap) {
  if (!out || outCap < 65) return -1;

  uint8_t enc_shuf[32];
  uint8_t enc[32];
  uint8_t plain[32];

  // 1) rebuild shuffled enc from nibble tables (mask off decoy high bits)
  for (size_t i = 0; i < 32; i++) {
    uint8_t h = (uint8_t)(kTserverKeyHi[i] & 0x0Fu);
    uint8_t l = (uint8_t)(kTserverKeyLo[i] & 0x0Fu);
    enc_shuf[i] = (uint8_t)((h << 4) | l);
  }

  // 2) unshuffle
  for (size_t j = 0; j < 32; j++) {
    uint8_t idx = kTserverKeyInvPerm[j];
    if (idx >= 32) {
      out[0] = 0;
      return -1;
    }
    enc[j] = enc_shuf[idx];
  }

  // 3) XOR masks (also stored shuffled → unshuffle masks the same way)
  for (size_t j = 0; j < 32; j++) {
    uint8_t idx = kTserverKeyInvPerm[j];
    uint8_t ma = kTserverKeyMaskA[idx];
    uint8_t mb = kTserverKeyMaskB[idx];
    plain[j] = (uint8_t)(enc[j] ^ ma ^ mb);
  }

  // 4) format hex without a contiguous "0123456789abcdef" string in .rodata
  for (size_t i = 0; i < 32; i++) {
    uint8_t b = plain[i];
    uint8_t hi = (uint8_t)((b >> 4) & 0x0Fu);
    uint8_t lo = (uint8_t)(b & 0x0Fu);
    // '0'..'9' then 'a'..'f' via arithmetic (no hex alphabet literal)
    out[i * 2]     = (char)(hi < 10 ? ('0' + hi) : ('a' + (hi - 10)));
    out[i * 2 + 1] = (char)(lo < 10 ? ('0' + lo) : ('a' + (lo - 10)));
  }
  out[64] = '\0';

  // wipe stack
  volatile uint8_t *w;
  w = enc_shuf; for (size_t i = 0; i < 32; i++) w[i] = 0;
  w = enc;      for (size_t i = 0; i < 32; i++) w[i] = 0;
  w = plain;    for (size_t i = 0; i < 32; i++) w[i] = 0;
  return 0;
}

const char *TserverClientApiKeyFingerprint(void) {
  return kTserverClientApiKeyFingerprint;
}

int TserverClientApiKeyEmbedOk(void) {
  uint32_t acc = 0;
  for (size_t i = 0; i < 32; i++) {
    acc |= kTserverKeyHi[i];
    acc |= kTserverKeyLo[i];
    acc |= kTserverKeyMaskA[i];
    acc |= kTserverKeyMaskB[i];
    acc |= kTserverKeyInvPerm[i];
  }
  return acc != 0 ? 0 : -1;
}

#ifdef __cplusplus
}
#endif
