#!/usr/bin/env bash
# Embed CLIENT_API_KEY as multi-layer XOR + interleaved nibble tables (anti-hex dump).
# Usage: TSERVER_CLIENT_API_KEY=hex64 bash embed_client_api_key.sh
# Output: src/TserverClientApiKeyData.gen.mm
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/src/TserverClientApiKeyData.gen.mm"
KEY="$(printf '%s' "${TSERVER_CLIENT_API_KEY:-}" | tr -d ' \r\n' | tr 'A-F' 'a-f')"

if [[ ! "$KEY" =~ ^[0-9a-f]{64}$ ]]; then
  echo "[embed_client_api_key] ERROR: TSERVER_CLIENT_API_KEY must be 64 hex chars" >&2
  exit 1
fi

MASK1_HEX="$(openssl rand -hex 32 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(32))')"
MASK2_HEX="$(openssl rand -hex 32 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(32))')"
PERM_SEED="$(openssl rand -hex 16 2>/dev/null || python3 -c 'import secrets; print(secrets.token_hex(16))')"

python3 - "$KEY" "$MASK1_HEX" "$MASK2_HEX" "$PERM_SEED" "$OUT" <<'PY'
import hashlib
import random
import sys

key_hex, m1_hex, m2_hex, perm_seed, out_path = sys.argv[1:6]
key = bytes.fromhex(key_hex)
key_fingerprint = hashlib.sha256(key_hex.encode("ascii")).hexdigest()
m1 = bytes.fromhex(m1_hex)
m2 = bytes.fromhex(m2_hex)
assert len(key) == 32 and len(m1) == 32 and len(m2) == 32

# Layered XOR
enc = bytes(a ^ b ^ c for a, b, c in zip(key, m1, m2))

# Deterministic shuffle of byte indices (anti contiguous hex dump of key material)
rng = random.Random(int.from_bytes(bytes.fromhex(perm_seed), "big"))
perm = list(range(32))
rng.shuffle(perm)
# Store shuffled enc: enc_shuf[i] = enc[perm[i]]
enc_shuf = bytes(enc[perm[i]] for i in range(32))
# inv_perm[perm[i]] = i  →  to restore: enc[j] = enc_shuf[inv[j]]
inv = [0] * 32
for i, p in enumerate(perm):
    inv[p] = i

# Split each byte into high/low nibble streams (16-byte pairs) so xxd won't show
# a clean 32-byte secret block after a single XOR pass.
hi = bytes((b >> 4) & 0x0F for b in enc_shuf)
lo = bytes(b & 0x0F for b in enc_shuf)
# Pad nibbles into full bytes with decoy high bits (random) so tables look like noise.
decoy1 = bytes.fromhex(perm_seed)
decoy2 = bytes(decoy1[i] ^ 0xA5 for i in range(16))
hi_store = bytes(((decoy1[i % 16] & 0xF0) | hi[i]) for i in range(32))
lo_store = bytes(((decoy2[i % 16] & 0xF0) | lo[i]) for i in range(32))

# Also scramble mask storage the same perm so offline XOR of co-located arrays fails.
m1_shuf = bytes(m1[perm[i]] for i in range(32))
m2_shuf = bytes(m2[perm[i]] for i in range(32))

def c_array(name, data, width=16):
    lines = []
    for i in range(0, len(data), width):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + width])
        lines.append(f"  {chunk}")
    return f"static const uint8_t {name}[{len(data)}] = {{\n" + ",\n".join(lines) + "\n};\n"

def c_u8_array(name, values):
    lines = []
    for i in range(0, len(values), 16):
        chunk = ", ".join(str(int(v)) for v in values[i:i + 16])
        lines.append(f"  {chunk}")
    return f"static const uint8_t {name}[{len(values)}] = {{\n" + ",\n".join(lines) + "\n};\n"

content = f"""// AUTO-GENERATED by scripts/embed_client_api_key.sh — do not edit.
// CLIENT_API_KEY anti-hex embed:
//  - dual XOR masks
//  - shuffled byte order (perm)
//  - split high/low nibble tables with decoy bits
//  - no contiguous 64-char hex alphabet / no plain key string
#include <stddef.h>
#include <stdint.h>
#include <string.h>

// Non-secret SHA-256 fingerprint of the 64-character CLIENT_API_KEY. This is
// release provenance only; it cannot authenticate a request or reconstruct key bytes.
static const char kTserverClientApiKeyFingerprint[] = "{key_fingerprint}";

{c_array("kTserverKeyHi", hi_store)}
{c_array("kTserverKeyLo", lo_store)}
{c_array("kTserverKeyMaskA", m1_shuf)}
{c_array("kTserverKeyMaskB", m2_shuf)}
{c_u8_array("kTserverKeyInvPerm", inv)}

#ifdef __cplusplus
extern "C" {{
#endif

// Reconstruct 64 lowercase hex chars into out[0..63], out[64]=0. Returns 0 on success.
int TserverFillClientApiKeyHex(char *out, size_t outCap) {{
  if (!out || outCap < 65) return -1;

  uint8_t enc_shuf[32];
  uint8_t enc[32];
  uint8_t plain[32];

  // 1) rebuild shuffled enc from nibble tables (mask off decoy high bits)
  for (size_t i = 0; i < 32; i++) {{
    uint8_t h = (uint8_t)(kTserverKeyHi[i] & 0x0Fu);
    uint8_t l = (uint8_t)(kTserverKeyLo[i] & 0x0Fu);
    enc_shuf[i] = (uint8_t)((h << 4) | l);
  }}

  // 2) unshuffle
  for (size_t j = 0; j < 32; j++) {{
    uint8_t idx = kTserverKeyInvPerm[j];
    if (idx >= 32) {{
      out[0] = 0;
      return -1;
    }}
    enc[j] = enc_shuf[idx];
  }}

  // 3) XOR masks (also stored shuffled → unshuffle masks the same way)
  for (size_t j = 0; j < 32; j++) {{
    uint8_t idx = kTserverKeyInvPerm[j];
    uint8_t ma = kTserverKeyMaskA[idx];
    uint8_t mb = kTserverKeyMaskB[idx];
    plain[j] = (uint8_t)(enc[j] ^ ma ^ mb);
  }}

  // 4) format hex without a contiguous "0123456789abcdef" string in .rodata
  for (size_t i = 0; i < 32; i++) {{
    uint8_t b = plain[i];
    uint8_t hi = (uint8_t)((b >> 4) & 0x0Fu);
    uint8_t lo = (uint8_t)(b & 0x0Fu);
    // '0'..'9' then 'a'..'f' via arithmetic (no hex alphabet literal)
    out[i * 2]     = (char)(hi < 10 ? ('0' + hi) : ('a' + (hi - 10)));
    out[i * 2 + 1] = (char)(lo < 10 ? ('0' + lo) : ('a' + (lo - 10)));
  }}
  out[64] = '\\0';

  // wipe stack
  volatile uint8_t *w;
  w = enc_shuf; for (size_t i = 0; i < 32; i++) w[i] = 0;
  w = enc;      for (size_t i = 0; i < 32; i++) w[i] = 0;
  w = plain;    for (size_t i = 0; i < 32; i++) w[i] = 0;
  return 0;
}}

const char *TserverClientApiKeyFingerprint(void) {{
  return kTserverClientApiKeyFingerprint;
}}

int TserverClientApiKeyEmbedOk(void) {{
  uint32_t acc = 0;
  for (size_t i = 0; i < 32; i++) {{
    acc |= kTserverKeyHi[i];
    acc |= kTserverKeyLo[i];
    acc |= kTserverKeyMaskA[i];
    acc |= kTserverKeyMaskB[i];
    acc |= kTserverKeyInvPerm[i];
  }}
  return acc != 0 ? 0 : -1;
}}

#ifdef __cplusplus
}}
#endif
"""
with open(out_path, "w", encoding="utf-8") as f:
    f.write(content)
print(f"[embed_client_api_key] wrote {out_path} (anti-hex: nibble+shuffle+dual-xor)")
PY
