#!/usr/bin/env python3
"""Generate a bounded ES256 public-key keyring for libAPIClient.a.

Input is comma-separated `kid=/absolute/public-key.pem` entries. Public keys are
not secrets, but DER bytes are split and masked so the verifier/keyring path is
less convenient to patch by a casual static edit.
"""
from __future__ import annotations

import argparse
import base64
import re
import secrets
import subprocess
from pathlib import Path


def c_array(name: str, data: bytes) -> str:
    chunks = []
    for index in range(0, len(data), 12):
        chunks.append("  " + ", ".join(f"0x{byte:02x}" for byte in data[index : index + 12]) + ",")
    return f"static const uint8_t {name}[{len(data)}] = {{\n" + "\n".join(chunks) + "\n};\n"


def public_x963(path: Path) -> bytes:
    output = subprocess.check_output(
        ["openssl", "ec", "-pubin", "-in", str(path), "-pubout", "-conv_form", "uncompressed", "-outform", "DER"],
        stderr=subprocess.DEVNULL,
    )
    # OpenSSL emits SubjectPublicKeyInfo. Apple SecKeyCreateWithData expects the
    # uncompressed ANSI X9.63 point for an EC public key (04 || X || Y).
    marker = len(output) - 65
    point = output[marker:] if marker >= 0 and output[marker] == 0x04 else b""
    if len(point) != 65:
        raise ValueError(f"public key is not a P-256 uncompressed point: {path}")
    return point


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--keys", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    entries = []
    for raw in args.keys.split(","):
        raw = raw.strip()
        if not raw:
            continue
        kid, separator, filename = raw.partition("=")
        kid = kid.strip()
        filename = filename.strip()
        if not separator or not re.fullmatch(r"[A-Za-z0-9._-]{1,64}", kid):
            raise ValueError("keyring entries must use kid=/absolute/public-key.pem")
        path = Path(filename)
        if not path.is_absolute() or not path.is_file():
            raise ValueError(f"public key does not exist: {path}")
        if any(existing_kid == kid for existing_kid, *_ in entries):
            raise ValueError(f"duplicate authorization key id: {kid}")
        public_point = public_x963(path)
        mask = secrets.token_bytes(len(public_point))
        sealed = bytes(left ^ right for left, right in zip(public_point, mask))
        entries.append((kid, sealed, mask, len(public_point)))
    if not 1 <= len(entries) <= 3:
        raise ValueError("authorization keyring requires one to three public keys")

    arrays = []
    rows = []
    for index, (kid, sealed, mask, length) in enumerate(entries):
        arrays.append(c_array(f"kLeaseKeyData{index}", sealed))
        arrays.append(c_array(f"kLeaseKeyMask{index}", mask))
        rows.append(f'  {{ "{kid}", kLeaseKeyData{index}, kLeaseKeyMask{index}, {length} }},')

    content = f"""// AUTO-GENERATED by scripts/generate_authorization_keyring.py — do not edit.
#include "TserverAuthorizationKeys.h"
#include <string.h>

{''.join(arrays)}
typedef struct {{
  const char *kid;
  const uint8_t *data;
  const uint8_t *mask;
  size_t length;
}} TserverLeasePublicKeyRow;

static const TserverLeasePublicKeyRow kLeaseKeys[] = {{
{chr(10).join(rows)}
}};

size_t TserverAuthorizationPublicKeyCount(void) {{
  return sizeof(kLeaseKeys) / sizeof(kLeaseKeys[0]);
}}

const char *TserverAuthorizationPublicKeyId(size_t index) {{
  return index < TserverAuthorizationPublicKeyCount() ? kLeaseKeys[index].kid : "";
}}

int TserverAuthorizationPublicKeyCopy(size_t index, uint8_t *out, size_t outCap) {{
  if (index >= TserverAuthorizationPublicKeyCount() || !out) return -1;
  const TserverLeasePublicKeyRow *row = &kLeaseKeys[index];
  if (outCap < row->length) return -1;
  for (size_t i = 0; i < row->length; i++) out[i] = (uint8_t)(row->data[i] ^ row->mask[i]);
  return (int)row->length;
}}

int TserverAuthorizationPublicKeyringReady(void) {{
  return TserverAuthorizationPublicKeyCount() > 0 ? 0 : -1;
}}
"""
    Path(args.out).write_text(content, encoding="utf-8")
    print(f"[authorization_keyring] wrote {args.out} (keys={len(entries)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
