#!/usr/bin/env python3
"""Generate sealed constant tables for libAPIClient (auto, no hand-picking).

Seals:
  - Sensitive path/marker strings used by package HTTP (anti-strings)
  - Numeric IDs / "offsets" style constants (anti-dump of plain tables)

Output:
  include/TserverSealedConstants.h
  src/TserverSealedConstants.gen.mm

Runtime decode via TserverSecureBlobOpen / helpers in the .mm file.
"""
from __future__ import annotations
import argparse
import secrets
import struct
from pathlib import Path

MAGIC = 0x31525354  # TSERVER_SECURE_BLOB_MAGIC


def keystream(key: bytes, n: int) -> bytes:
    s0 = int.from_bytes(key[0:4], "little")
    s1 = int.from_bytes(key[4:8], "little")
    s2 = int.from_bytes(key[8:12], "little")
    s3 = int.from_bytes(key[12:16], "little")
    if (s0 | s1 | s2 | s3) == 0:
        s0, s1, s2, s3 = 0xA5A5A5A5, 0x3C6EF372, 0x1F83D9AB, 0x9E3779B9
    out = bytearray(n)
    for i in range(n):
        t = (s0 ^ ((s0 << 11) & 0xFFFFFFFF)) & 0xFFFFFFFF
        s0, s1, s2 = s1, s2, s3
        s3 = (s3 ^ (s3 >> 19) ^ t ^ (t >> 8)) & 0xFFFFFFFF
        out[i] = s3 & 0xFF
    return bytes(out)


def seal(plain: bytes) -> bytes:
    key = secrets.token_bytes(16)
    ks = keystream(key, len(plain))
    enc = bytes(a ^ b for a, b in zip(plain, ks))
    return struct.pack("<II", MAGIC, len(plain)) + key + enc


def c_array(name: str, data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        lines.append(f"  {chunk},")
    return f"static const unsigned char {name}[] = {{\n" + "\n".join(lines) + "\n};\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-mm", required=True)
    ap.add_argument("--out-h", required=True)
    args = ap.parse_args()

    # --- String table (NUL-separated) — package API paths / hosts fragments / headers ---
    strings = [
        "/tokenapi",
        "/tokenapi/bootstrap",
        "/tokenapi/transport/handshake",
        "/v1/package",
        "/v1/package/license/activate",
        "/v1/package/license/verify",
        "x-ts-enc",
        "x-ts-sid",
        "x-ts-timestamp",
        "x-ts-nonce",
        "x-ts-signature",
        "application/json",
        "proxy.huutien.store",
        "server.huutien.store",
        "tserver-transport-v1|",
        "tserver-ecdh-v1|",
        "pkg_",
        "TRANSPORT_SESSION_OK",
        "BAD_TRANSPORT_CRYPTO",
        "INVALID_CLIENT_API_KEY",
        "BAD_RESPONSE_SIGNATURE",
        "authorizationLease",
        "authorizationLeaseVersion",
        "signatures",
        "packageAudience",
        "packageSession",
        "capabilities",
        "tserver-native-sdk",
        "com.tserver.auth",
        "lease_display_v2",
        "https://",
        "tserver",
        "x-client-api-key",
        "x-api-key",
        "/v1/member-api",
        "/packages",
        "/online",
        "/keys",
        "/keys/remaining",
        "/transport/handshake",
        "/p/",
        "/p/package/start",
        "/install",
        "src=app",
        "Authorization",
        "Bearer ",
    ]
    str_plain = b"\0".join(s.encode("utf-8") for s in strings) + b"\0"
    str_blob = seal(str_plain)

    # --- Numeric "offset"/ID table (u32) — internal markers, not game offsets ---
    # These are hashed/IDs used as anti-tamper tokens & table indices.
    nums = [
        0x54535231,  # 'TSR1'
        0x00010000,  # schema
        0x00000010,  # key len
        0x00000020,  # session key len
        0x00000E10,  # 3600s-ish
        0x00000708,  # 1800s
        0xA5A5A5A5,
        0x3C6EF372,
        0x1F83D9AB,
        0x9E3779B9,
        0x00000058,  # prologue scan len-ish
        0x00000010,  # snap bytes
        0xDEADBEEF,
        0x00C0FFEE,
        0x0BADF00D,
        0xFEEDFACE,
    ]
    num_plain = b"".join(struct.pack("<I", n & 0xFFFFFFFF) for n in nums)
    num_blob = seal(num_plain)

    header = f"""// AUTO-GENERATED by scripts/generate_sealed_sdk_constants.py — do not edit.
#pragma once
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

// Sealed string table (NUL-separated). Decode with TserverSealedStringsCopy.
int TserverSealedStringsCopy(char *out, size_t outCap);
// Returns pointer to Nth string inside a thread-local decode buffer (valid until next call).
const char *TserverSealedStringAt(size_t index);

// Sealed u32 table. out[i] = value. Returns count or -1.
int TserverSealedU32TableCopy(uint32_t *out, size_t maxCount);

// Known indices for string table (keep in sync with generator list order).
enum {{
  kTserverSealedStr_TokenApi = 0,
  kTserverSealedStr_TokenApiBootstrap = 1,
  kTserverSealedStr_TransportHandshake = 2,
  kTserverSealedStr_V1Package = 3,
  kTserverSealedStr_V1PackageActivate = 4,
  kTserverSealedStr_V1PackageVerify = 5,
  kTserverSealedStr_XTsEnc = 6,
  kTserverSealedStr_XTsSid = 7,
  kTserverSealedStr_XTsTimestamp = 8,
  kTserverSealedStr_XTsNonce = 9,
  kTserverSealedStr_XTsSignature = 10,
  kTserverSealedStr_ApplicationJson = 11,
  kTserverSealedStr_ApiHost = 12,
  kTserverSealedStr_ApexHost = 13,
  kTserverSealedStr_TransportV1Prefix = 14,
  kTserverSealedStr_EcdhV1Prefix = 15,
  kTserverSealedStr_PkgPrefix = 16,
  kTserverSealedStr_TransportSessionOk = 17,
  kTserverSealedStr_BadTransportCrypto = 18,
  kTserverSealedStr_InvalidClientApiKey = 19,
  kTserverSealedStr_BadResponseSignature = 20,
  kTserverSealedStr_AuthorizationLease = 21,
  kTserverSealedStr_AuthorizationLeaseVersion = 22,
  kTserverSealedStr_Signatures = 23,
  kTserverSealedStr_PackageAudience = 24,
  kTserverSealedStr_PackageSession = 25,
  kTserverSealedStr_Capabilities = 26,
  kTserverSealedStr_AuthorizationAudience = 27,
  kTserverSealedStr_KeychainService = 28,
  kTserverSealedStr_KeychainLeaseAccount = 29,
  kTserverSealedStr_HttpsScheme = 30,
  kTserverSealedStr_Issuer = 31,
  kTserverSealedStr_XClientApiKey = 32,
  kTserverSealedStr_XApiKey = 33,
  kTserverSealedStr_V1MemberApi = 34,
  kTserverSealedStr_MemberPackages = 35,
  kTserverSealedStr_MemberOnline = 36,
  kTserverSealedStr_MemberKeys = 37,
  kTserverSealedStr_MemberKeysRemaining = 38,
  kTserverSealedStr_TransportHandshakePath = 39,
  kTserverSealedStr_ProfileWebPrefix = 40,
  kTserverSealedStr_ProfileStartPrefix = 41,
  kTserverSealedStr_ProfileInstall = 42,
  kTserverSealedStr_ProfileSrcApp = 43,
  kTserverSealedStr_HeaderAuthorization = 44,
  kTserverSealedStr_BearerPrefix = 45
}};

#ifdef __cplusplus
}}
#endif
"""

    mm = f"""// AUTO-GENERATED by scripts/generate_sealed_sdk_constants.py — do not edit.
#import "TserverSealedConstants.h"
#import "TserverSecureBlob.h"
#include <string.h>
#include <stdlib.h>
#include <pthread.h>

{c_array("kTserverSealedStringBlob", str_blob)}
{c_array("kTserverSealedU32Blob", num_blob)}

static pthread_key_t gStrKey;
static pthread_once_t gStrOnce = PTHREAD_ONCE_INIT;
static void TserverStrKeyMake(void) {{
  pthread_key_create(&gStrKey, free);
}}

int TserverSealedStringsCopy(char *out, size_t outCap) {{
  if (!out || outCap == 0) return -1;
  int n = TserverSecureBlobOpen(kTserverSealedStringBlob, sizeof(kTserverSealedStringBlob), out, outCap);
  return n;
}}

const char *TserverSealedStringAt(size_t index) {{
  pthread_once(&gStrOnce, TserverStrKeyMake);
  char *buf = (char *)pthread_getspecific(gStrKey);
  if (!buf) {{
    buf = (char *)malloc(4096);
    if (!buf) return "";
    pthread_setspecific(gStrKey, buf);
  }}
  int n = TserverSealedStringsCopy(buf, 4096);
  if (n <= 0) return "";
  size_t i = 0;
  const char *p = buf;
  const char *end = buf + n;
  while (p < end) {{
    if (i == index) return p;
    size_t len = strnlen(p, (size_t)(end - p));
    p += len + 1;
    i++;
  }}
  return "";
}}

int TserverSealedU32TableCopy(uint32_t *out, size_t maxCount) {{
  return TserverSecureBlobOpenU32Table(kTserverSealedU32Blob, sizeof(kTserverSealedU32Blob), out, maxCount);
}}
"""

    Path(args.out_h).write_text(header, encoding="utf-8")
    Path(args.out_mm).write_text(mm, encoding="utf-8")
    print(f"[sealed_sdk_constants] wrote {args.out_h}")
    print(f"[sealed_sdk_constants] wrote {args.out_mm} (strings={len(strings)}, u32={len(nums)})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
