// AUTO-GENERATED by scripts/generate_sealed_sdk_constants.py — do not edit.
#pragma once
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Sealed string table (NUL-separated). Decode with TserverSealedStringsCopy.
int TserverSealedStringsCopy(char *out, size_t outCap);
// Returns pointer to Nth string inside a thread-local decode buffer (valid until next call).
const char *TserverSealedStringAt(size_t index);

// Sealed u32 table. out[i] = value. Returns count or -1.
int TserverSealedU32TableCopy(uint32_t *out, size_t maxCount);

// Known indices for string table (keep in sync with generator list order).
enum {
  kTserverSealedStr_TokenApi = 0,
  kTserverSealedStr_TokenApiBootstrap = 1,
  kTserverSealedStr_TransportHandshake = 2,
  kTserverSealedStr_V1Package = 3,
  kTserverSealedStr_V1PackageActivate = 4,
  kTserverSealedStr_V1PackageVerify = 5,
  kTserverSealedStr_XTsEnc = 6,
  kTserverSealedStr_XTsSid = 7,
  kTserverSealedStr_XTsTimestamp = 8,
  kTserverSealedStr_XTsNonce = 9,
  kTserverSealedStr_XTsSignature = 10,
  kTserverSealedStr_ApplicationJson = 11,
  kTserverSealedStr_ApiHost = 12,
  kTserverSealedStr_ApexHost = 13,
  kTserverSealedStr_TransportV1Prefix = 14,
  kTserverSealedStr_EcdhV1Prefix = 15,
  kTserverSealedStr_PkgPrefix = 16,
  kTserverSealedStr_TransportSessionOk = 17,
  kTserverSealedStr_BadTransportCrypto = 18,
  kTserverSealedStr_InvalidClientApiKey = 19,
  kTserverSealedStr_BadResponseSignature = 20,
  kTserverSealedStr_AuthorizationLease = 21,
  kTserverSealedStr_AuthorizationLeaseVersion = 22,
  kTserverSealedStr_Signatures = 23,
  kTserverSealedStr_PackageAudience = 24,
  kTserverSealedStr_PackageSession = 25,
  kTserverSealedStr_Capabilities = 26,
  kTserverSealedStr_AuthorizationAudience = 27,
  kTserverSealedStr_KeychainService = 28,
  kTserverSealedStr_KeychainLeaseAccount = 29,
  kTserverSealedStr_HttpsScheme = 30,
  kTserverSealedStr_Issuer = 31,
  kTserverSealedStr_XClientApiKey = 32,
  kTserverSealedStr_XApiKey = 33,
  kTserverSealedStr_V1MemberApi = 34,
  kTserverSealedStr_MemberPackages = 35,
  kTserverSealedStr_MemberOnline = 36,
  kTserverSealedStr_MemberKeys = 37,
  kTserverSealedStr_MemberKeysRemaining = 38,
  kTserverSealedStr_TransportHandshakePath = 39,
  kTserverSealedStr_ProfileWebPrefix = 40,
  kTserverSealedStr_ProfileStartPrefix = 41,
  kTserverSealedStr_ProfileInstall = 42,
  kTserverSealedStr_ProfileSrcApp = 43,
  kTserverSealedStr_HeaderAuthorization = 44,
  kTserverSealedStr_BearerPrefix = 45
};

#ifdef __cplusplus
}
#endif
